version: '3'
services:
  grafana:
    image: grafana/grafana:5.4.3
    restart: always
    ports: 
      - 8081:3000
    environment: 
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes: 
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
    driver: local